"""Exercise the time map with real Chromium, including stories and text fallback."""
import argparse
from functools import partial
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
import json
from pathlib import Path
import threading
from playwright.sync_api import sync_playwright, expect

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--output', default='/tmp/notes-review')
args = parser.parse_args()
output = Path(args.output)
output.mkdir(parents=True, exist_ok=True)
class QuietHandler(SimpleHTTPRequestHandler):
    def log_message(self, *args):
        pass
server = ThreadingHTTPServer(('127.0.0.1', 0), partial(QuietHandler, directory=str(ROOT/'docs')))
threading.Thread(target=server.serve_forever, daemon=True).start()
base = f'http://127.0.0.1:{server.server_port}/'
results = []
errors = []
def check(name, condition):
    assert condition, name
    results.append(name)
def ready(page, query=''):
    page.goto(base+'historical-notes.html'+query, wait_until='networkidle')
    page.wait_for_function('window.__notes && document.getElementById("notes-loading").hidden')
def shot(page, name):
    page.evaluate('window.scrollTo(0,0)')
    page.wait_for_timeout(100)
    page.screenshot(path=str(output/f'{name}.png'), full_page=True, animations='disabled')
try:
    with sync_playwright() as pw:
        browser=pw.chromium.launch(args=['--use-angle=swiftshader','--enable-unsafe-swiftshader'])
        context=browser.new_context(viewport={'width':1440,'height':1000},reduced_motion='reduce')
        page=context.new_page()
        page.on('pageerror',lambda e:errors.append(str(e)))
        ready(page)
        check('Real Three.js map with all publication instances',page.evaluate('!!__notes.scene.renderer.getContext() && __notes.scene.posts.count===__notes.model.counts.total && !!__notes.scene.mapMesh'))
        check('Intro has three source-based story choices',page.locator('#notes-featured-stories button').count()==3)
        check('Full record list contains every publication',page.locator('#notes-twin .notes-record-list > li').count()==136)
        check('No desktop page overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        check('Year scale and geography labels exist',page.locator('.notes-year-tick').count()>=8 and page.locator('.notes-city-label').count()>20)
        shot(page,'desktop-home')
        page.locator('#btn-look').click()
        page.wait_for_timeout(500)
        before=page.evaluate('__notes.scene.frames')
        page.wait_for_timeout(350)
        check('Reduced motion rests without continuous rendering',page.evaluate('__notes.scene.frames')-before<=2)
        page.locator('#notes-year-enabled').check()
        page.locator('#notes-year').fill('1938')
        page.locator('#notes-year').dispatch_event('change')
        check('Year slice updates state and URL',page.evaluate('__notes.state.year')==1938 and 'year=1938' in page.url)
        expected=page.evaluate('__notes.model.publications.filter(p=>p.yearFounded!==null && p.yearFounded<=1938 && (p.active||p.yearCeased!==null&&p.yearCeased>=1938)).length')
        check('Year count uses only recorded spans',page.locator('#notes-year-count').inner_text().startswith(str(expected)+' '))
        shot(page,'desktop-year')
        page.locator('#notes-year-enabled').uncheck()
        page.locator('#btn-find').click()
        page.locator('#notes-evidence').select_option('active')
        check('Active filter matches archive',page.locator('#notes-publications button').count()==17)
        page.locator('#notes-city').select_option('Newark')
        expected=page.evaluate('__notes.model.publications.filter(p=>p.active&&p.city==="Newark").length')
        check('City and status filters combine',page.locator('#notes-publications button').count()==expected)
        page.locator('#notes-clear').click()
        page.locator('#notes-search').fill('Landscape')
        page.locator('#notes-publications button').first.click()
        expect(page.locator('#notes-panel-title')).to_have_text('The Landscape')
        check('Selected publication is shareable', 'pub=34' in page.url)
        shot(page,'desktop-record')
        page.locator('#btn-close-panel').click()
        page.locator('#btn-find').click()
        page.locator('#notes-clear').click()
        page.locator('#btn-close-find').click()
        page.locator('[data-notes-view="flat"]').click()
        check('Flat chart labels time and publication rows',page.locator('.notes-flat-row').count()==136 and page.locator('.notes-flat-axis').is_visible())
        page.locator('.notes-flat-row[data-publication="38"]').click()
        expect(page.locator('#notes-panel-title')).to_have_text('New Jersey Trumpet')
        check('Flat record keeps the view',page.evaluate('__notes.state.view')=='flat')
        shot(page,'flat-timeline')
        page.locator('#btn-close-panel').click()
        page.locator('[data-notes-view="map"]').click()
        # Pick a real instance through its projected centre after scrolling the page.
        page.evaluate('__notes.scene.frame([34],0)')
        page.locator('#notes-canvas').scroll_into_view_if_needed()
        page.wait_for_timeout(100)
        point=page.evaluate('''async()=>{const T=await import('three');const p=__notes.model.byId.get(34);const v=new T.Vector3(p.x,(p.startY+p.endY)/2,p.z).project(__notes.scene.camera);const r=document.getElementById('notes-canvas').getBoundingClientRect();return {x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2};}''')
        page.mouse.click(point['x'],point['y'])
        expect(page.locator('#notes-panel-title')).to_have_text('The Landscape')
        check('Raycast selects a visible geographical post',page.evaluate('__notes.state.publication')==34)
        page.locator('#btn-close-panel').click()
        page.locator('#notes-canvas').focus()
        page.keyboard.press('Home');page.keyboard.press('Enter')
        check('Keyboard opens a publication',page.locator('#notes-panel').is_visible())
        page.keyboard.press('Escape')
        check('Escape closes the publication',page.locator('#notes-panel').is_hidden())
        page.locator('#btn-stories').click()
        page.locator('#notes-story-list [data-story="story-004"]').click()
        expect(page.locator('#notes-panel')).to_be_visible()
        page.locator('#btn-next').click()
        check('Story next changes stop and URL',page.evaluate('__notes.state.stop')==1 and 'stop=1' in page.url)
        shot(page,'story-echo')
        # The data includes source gaps and later retrospectives. Check each real stop.
        stories=page.evaluate('__notes.model.stories.map(s=>({id:s.id,stops:s.stops.map(t=>({id:t.eventId,title:t.event.title,description:t.event.description,clip:t.clipping?.webPath||null}))}))')
        for story in stories:
            for index,stop in enumerate(story['stops']):
                page.evaluate('([id,i])=>__notes.showStop(id,i)',[story['id'],index])
                expect(page.locator('#notes-panel-title')).to_have_text(stop['title'])
                check(f"{story['id']} stop {index+1} retains source text",stop['description'] in page.locator('#notes-panel-content').inner_text())
                if stop['clip']:
                    check(f"{story['id']} stop {index+1} uses matched image",page.locator('#notes-panel-content img').get_attribute('src')==stop['clip'])
        page.evaluate('__notes.showStop("story-010",1)')
        shot(page,'story-hop')
        page.evaluate('__notes.publication(34,{move:false})')
        page.locator('[data-action="back-story"]').click()
        check('Record returns to the same story stop',page.evaluate('__notes.state.story==="story-010"&&__notes.state.stop===1&&__notes.state.mode==="story"'))
        page.locator('#btn-leave').click()
        check('Leaving story clears story URL', 'story=' not in page.url)
        page.go_back(wait_until='networkidle')
        check('Browser back restores story',page.evaluate('__notes.state.story')=='story-010')
        ready(page,'?story=story-004&stop=2')
        check('Story deep link restores exact stop',page.evaluate('__notes.state.stop===2&&__notes.state.story==="story-004"'))
        page.goto(base+'woven.html?view=woven&pub=1#woven-twin',wait_until='networkidle')
        page.wait_for_function('window.__notes?.state.publication===1')
        check('Old URL forwards selection and list anchor',page.url.split('?')[0].endswith('historical-notes.html') and page.locator('#notes-list-disclosure').evaluate('(e)=>e.open'))
        for width in [320,390,768]:
            page.set_viewport_size({'width':width,'height':844})
            ready(page)
            check(f'No page overflow at {width}px',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
            check(f'Map is usable at {width}px',page.locator('#notes-canvas').bounding_box()['height']>=280)
            shot(page,f'mobile-{width}-home')
            page.locator('#notes-featured-stories [data-story="story-004"]').click()
            check(f'Story remains available at {width}px',page.locator('#notes-panel-title').is_visible() and page.locator('#btn-next').is_visible())
            shot(page,f'mobile-{width}-story')
        ready(page,'?nogl=1&story=story-004&stop=1')
        check('Forced text path keeps story and full archive',page.locator('#notes-list-disclosure').evaluate('(e)=>e.open') and page.locator('#notes-panel-title').is_visible() and page.locator('#notes-twin .notes-record-list > li').count()==136)
        shot(page,'text-fallback')
        # Real WebGL loss must release scene and keep text interaction.
        ready(page)
        page.evaluate('document.getElementById("notes-canvas").dispatchEvent(new Event("webglcontextlost",{cancelable:true}))')
        check('Context loss switches to flat chart',page.evaluate('__notes.state.view')=='flat' and page.locator('.notes-flat-axis').is_visible())
        partial=browser.new_page(viewport={'width':1280,'height':900})
        partial.route('**/data/map-publications.json',lambda route:route.abort())
        ready(partial,'?pub=31')
        check('Missing coordinates preserve the flat archive and record',partial.evaluate('__notes.state.view')=='flat' and partial.locator('#notes-panel-title').inner_text()=='The Echo')
        partial.close()
        empty=browser.new_page(viewport={'width':1280,'height':900})
        empty.route('**/data/events.json',lambda route:route.fulfill(status=200,content_type='application/json',body='{"events":[]}'))
        ready(empty,'?nogl=1&story=story-004')
        check('Missing events keep the story overview', 'No documented stops' in empty.locator('#notes-panel-content').inner_text())
        empty.close()
        failed=browser.new_page()
        failed.route('**/data/publications.json',lambda route:route.abort())
        failed.goto(base+'historical-notes.html',wait_until='networkidle')
        expect(failed.locator('#notes-loading')).to_contain_text('could not load')
        check('Failed data has a visible recovery message',True)
        check('No browser errors',not errors)
        browser.close()
    print(f'PASS: {len(results)} time map browser checks')
finally:
    server.shutdown()
    (output/'results.json').write_text(json.dumps({'checks':results,'pageErrors':errors},indent=2)+'\n')
